name: polymer_sandbox
description: Polymer web demo
dependencies:
  http_server: any
  polymer: any
  route: any
dev_dependencies:
  unittest: any
#transformers:
#  polymer:
#    entry_points: web/index.html